name: formatting

on: [push, pull_request]

jobs:
  formatting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: printing rust version
      run: rustc --version
    - name: printing cargo version
      run: cargo --version
    - name: installing fpcli
      run: cargo install fpcli
    - name: running ls
      run: ls -l
    - name: running pwd
      run: pwd
    - name: checking for linting issues with the Flatpak manifests
      run: bash ../../scripts/lint.sh
